language: rust

dist: xenial
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-setuptools

install:
  - pip3 install --user tensorflow==1.13.1

custom:
  test: &test
    stage: test
    cache:
      cargo: true
      pip: true
    script:
      - ./ci/run_tests.sh

jobs:
  include:
    - <<: *test
      os: linux
      rust: nightly-2019-03-08
      python: 3.7
    - <<: *test
      os: linux
      rust: nightly
      python: 3.7
