language: rust

dist: xenial
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
  - sudo apt-get install python3.7-dev
  - ls /usr/bin/python* -1
  - wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
  - sudo python3.7 /tmp/get-pip.py

install:
  - pip3 install --user setuptools
  - pip3 install --user tensorflow==1.13.1

custom:
  test: &test
    stage: test
    cache:
      cargo: true
      pip: true
    script:
      - ./ci/run_tests.sh

jobs:
  include:
    - <<: *test
      os: linux
      rust: nightly-2019-03-08
    - <<: *test
      os: linux
      rust: nightly
