language: rust

dist: xenial
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.7
  - sudo apt-get install -y python3-pip python3-setuptools
  - ls /usr/bin/python* -1

install:
  - pip3 install --user tensorflow==1.13.1

custom:
  test: &test
    stage: test
    cache:
      cargo: true
      pip: true
    script:
      - ./ci/run_tests.sh

jobs:
  include:
    - <<: *test
      os: linux
      rust: nightly-2019-03-08
    - <<: *test
      os: linux
      rust: nightly
