language: rust

dist: xenial
sudo: false

python: 3.7

install:
  - pip install tensorflow==1.13.1 --progress-bar off

custom:
  test: &test
    stage: test
    cache:
      cargo: true
    script:
      - ./ci/run_tests.sh

jobs:
  include:
    - <<: *test
      os: linux
      rust: nightly-2019-03-08
    - <<: *test
      os: linux
      rust: nightly
